server:
  port: 9000
  servlet:
    contextPath: /cep/ 
spring:
  application:
    name: Cep - Api
  jpa.open-in-view: false  

security:
  jwt:
    header: ${JWT_HEADER:Authorization}
    prefix: ${JWT_PREFIX:Bearer}
    secret: ${JWT_SECRET:10E9F239E3523081B76C3B71E26BF1C29D8D6E5DC11583A0BBA534BF8CBC338A}
      
info:
  app:
    encoding: '@project.build.sourceEncoding@'
  java:
    source: '@java.version@'
    target: '@java.version@'
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'  